server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: duang-ai-service

  ai:
    openai:
      api-key:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max

#  ai:
#    openai:
#      api-key:
#      base-url: https://api.deepseek.com
#      chat:
#        options:
#          model: deepseek-chat

#  ai:
#    openai:
#      api-key:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#    chat:
#      options:
#        model: qwen-vl-max

#vl:
#  api-key:
#  base-url: https://dashscope.aliyuncs.com/compatible-mode
#  chat:
#    options:
#      model: qwen-vl-max